---
title: Componentes Passivos em RF 
subtitle: Laboratório 07
author:
  - name: Bruno Alexandre Fraga
    email: bruno.fraga@posgrad.ufsc.br
    affiliations: 
        - id: some-tech
          name: Universidade Federal de Santa Catarina
          department: Departamento de Engenharia Elétrica e Eletrônica
          address: R. Delfino Conti
          city: Florianópolis
          state: Santa Catarina
          postal-code: 88040-370
abstract: |
  Este trabalho tem por objetivo consolidar a técnica de projeto de redes de casamento de impedância, em especial a técnica pela rede L. Para isso, é proposto realizar o casamento de impedância da saída de um amplificador para uma carga de 50 $\Omega$ de modo que a eficiência da potência dissipada na carga seja de 80%. Após algumas análises o projeto foi concluído com sucesso e realizada uma simulação Monte Carlo com 100 iterações para verificar a robustez do projeto por técnicas estatísticas. Os resultados obtidos foram brevemente discutidos.
keywords: 
  - Robustez
  - Adaptação de impedância
  - Análise estatística
date: last-modified
bibliography: bibliography.bib
format:
  elsevier-pdf:
    include-in-header:
      - text: |
          \usepackage{steinmetz}
          \usepackage[a4paper, margin=1in]{geometry}
          \usepackage{graphicx} % Required for inserting images
          \usepackage{circuitikz}
          \usepackage{amsmath}
          \usepackage{amssymb}
          \usepackage{amsthm}

          \newcommand{\parallelsum}{\mathbin{\!/\mkern-5mu/\!}}
    keep-tex: true
    journal:
      name: RF Circuits
      formatting: preprint
      # model: 3p # Don't set a model with preprint
      cite-style: number
---


# Prelab



# Laboratório

## Perda por inserção no Bias-Tee

### Análise do circuito

A perda por inserção, $\text{IL}$ é definida como @steer2019microwavev3.

$$
  \text{IL}=\frac{P_{L1}}{P_{L2}}
$$

em que $P_{L1}$ é a potência dissipada na carga sem o dispositivo a ser medido (DUT, do inglês *Device Under Test*) e $P_{L2}$ é o dispositivo a ser medido com o DUT acoplado ao circuito de medição.

```{=latex}
\begin{figure}[h]
  \centering
  \begin{circuitikz}[american]
	  \draw (0.5, -1.5) coordinate(point1) to[vsource, l=$V_s$] ++(0, -2) to[short] ++(4.5, 0) coordinate(point2) ;
	  \draw (point1) to[R, l=$R_s$] ++(0, 2) to[short, -*] ++(4.5, 0) to[R, l=$R_L$, i>^=$I_{L1}$, *-] (point2) ;

    % Add the marker for V_{L1}
    \node at (5, 0.5) [above right] [above] {$V_{L1}$};
  \end{circuitikz}
  \caption{Circuito sem \textit{bias-Tee}}
  \label{fig:circuit-no-biasTee}
\end{figure}
```

O circuito apresentado na Fig.\ref{fig:circuit-no-biasTee} está sem o DUT. Dessa forma, é possível calcular a potência entregue à carga $R_L$ antes do acoplamento do DUT.

$$
  P_{L1}=\frac{1}{2}\mathfrak{R}\left\{V_{L1}I_{L1}^*\right\}
$$

No caso do circuito da Fig. \ref{fig:circuit-no-biasTee} a tensão sob a carga é dada por (utilizando um divisor de tensão)

$$
  V_{L1}=V_s\frac{R_L}{R_s+R_L}
$$ {#eq-voltage-before}

A corrente de carga, $I_{L1}$, para essa configuração é dada por

$$
  I_{L1}=\frac{V_s}{R_s+R_L}
$$

Como a impedância é totalmente resistiva, sabe-se que $I_{L1}=I_{L1}^*$ e tanto $V_{L1}$ quanto $I_{L1}$ são totalmente reais. Dessa forma, a potência, $P_{L1}$ é obtida por

$$
  P_{L1}=\frac{V_s^2R_L}{2\left(R_s+R_L\right)^2}
$$

Para realizar a análise do circuito com o *bias-Tee* refere-se à Fig.\ref{fig:circuit-biasTee}.

```{=latex}
\begin{figure}[h]
  \centering
  \begin{circuitikz}[american]
	  \draw (1, -1) coordinate(point1) to[R, l=$R_s$] ++(0, -2) to[vsource, l=$V_s$] ++(0, -1.5) to[short] ++(3, 0) coordinate(point2) node[ground]{} ;
	  \draw (point1) to[C, l=C, a=$X_C$, i^>=$I_s$, -*] ++(3, 0) coordinate(point3) to[L, l=L, a=$X_L$, i>^=$I_{dc}$, *-] (point2) ;
	  \draw (point3) to[short, *-] ++(2, 0) to[R, l=$R_L$, i>^=$I_{L2}$] ++(0, -3.5) to[short] (point2) ;
  
    % Add the marker for V_{L2}
    \node at (point3) [above] {$V_{L2}$};
  \end{circuitikz}
  \caption{Circuito com \textit{bias-Tee}}
  \label{fig:circuit-biasTee}
\end{figure}
```

Logo de início, já é possível verificar que a tensão $V_{L2}$ é a tensão que opera sobre a resistência de carga. Conhecendo $V_{L2}$, também é possível obter a corrente que opera sob essa resistência, cuja relação é dada a seguir

$$
 I_{L2}=\frac{V_{L2}}{R_L}
$$

Pela lei de Kirchhoff de correntes, pode-se estabelecer a seguinte relação

$$
  \begin{split}
    I_s&=I_\text{dc}+\text{IL}\implies\\
    \frac{V_s-V_{L2}}{R_s+X_c}&=\frac{V_{L2}}{X_L}+\frac{V_{L2}}{R_L}\implies\\
    \frac{V_s}{R_s+X_c}&=V_{L2}\left(\frac{1}{X_L}+\frac{1}{R_L}+\frac{1}{R_s+X_c}\right)\implies\\
    \frac{V_s}{R_s+X_c}&=V_{L2}\left[\frac{(R_L+X_L)(R_s+X_C)+X_LR_L}{X_LR_L(R_s+X_C)}\right]\implies\\
    V_s&=V_{L2}\left[\frac{(R_L+X_L)(R_s+X_C)+X_LR_L}{X_LR_L}\right]\implies\\
    V_{L2}&=\frac{V_sX_LR_L}{(R_L+X_L)(R_s+X_C)+X_LR_L}\implies\\
  \end{split}
$$

em que a impedância do indutor é $X_L=j\omega L$ e a impedância do capacitor é $X_C=\left(j\omega C\right)^{-1}$.

Se for adotada a suposição de que $X_L=\omega L$ e $X_C=\left(\omega C\right)^{-1}$. A tensão $V_{L2}$ é dada por


$$
  \begin{split}
    V_{L2}&=\frac{jV_sX_LR_L}{(R_L+jX_L)(R_s-jX_C)+jX_LR_L}\implies\\
    &=\frac{jV_sX_LR_L}{(R_LR_s+X_LX_C)+j(X_LR_s+X_LR_L-R_LX_C)}\implies\\
    &=V_sX_LR_L\frac{(X_LR_s+X_LR_L-R_LX_C)+j(R_LR_s+X_LX_C)}{(R_LR_s+X_LX_C)^2+(X_LR_s+X_LR_L-R_LX_C)^2}
  \end{split}
$$

Sendo a tensão $V_{L2}$ conhecida, é possível calcular facilmente a corrente $I_{L2}$ como se segue

$$
  I_{L2}=\frac{V_{L2}}{R_L}=V_sX_L\frac{(X_LR_s+X_LR_L-R_LX_C)+j(R_LR_s+X_LX_C)}{(R_LR_s+X_LX_C)^2+(X_LR_s+X_LR_L-R_LX_C)^2}
$$

Entretanto, para o cálculo da potência, é necessário o conjugado da corrente, ou seja,

$$
  I_{L2}^*=V_sX_L\frac{(X_LR_s+X_LR_L-R_LX_C)-j(R_LR_s+X_LX_C)}{(R_LR_s+X_LX_C)^2+(X_LR_s+X_LR_L-R_LX_C)^2}
$$

Seguindo com o cálculo, tem-se que

$$
  \begin{split}
    V_{L2}I_{L2}^*&=V_s^2X_L^2R_L\frac{(R_LR_s+X_LX_C)^2+(X_LR_s+X_LR_L-R_LX_C)^2}{\left[(R_LR_s+X_LX_C)^2+(X_LR_s+X_LR_L-R_LX_C)^2\right]^2}\implies\\
    &=\frac{V_s^2X_L^2R_L}{(R_LR_s+X_LX_C)^2+(X_LR_s+X_LR_L-R_LX_C)^2}
  \end{split}
$$

Dessa forma, a potência sobre a carga com o DUT acoplado ao circuito de medição é dado por

$$
  P_{L2}=\frac{1}{2}\mathfrak{R}\left\{V_{L2}I_{L2}^*\right\}=\frac{V_s^2X_L^2R_L}{2(R_LR_s+X_LX_C)^2+2(X_LR_s+X_LR_L-R_LX_C)^2}
$$

Dessa forma, é possível calcular a perda por inserção, $\text{IL}$ como

$$
  \begin{split}
    \text{IL}&=\frac{(R_LR_s+X_LX_C)^2+(X_LR_s+X_LR_L-R_LX_C)^2}{X_L^2\left(R_s+R_L\right)^2}
  \end{split}
$$ {#eq-insertion-loss}

Entrentanto, essa equação é bem complicada e de difícil solução. Uma outra maneira é obter a função de transferência do *bias-Tee* e calcular a potência dissipada na carga. Essa abordagem parece ser bem interessante, uma vez que é possível utilizar os conhecimentos de síntese de filtros para obter o *insertion loss* desejado.

### Função de Transferência

A análise inicia-se buscando pela função de transferência do circuito com o *bias-tee* acoplado. Toma-se como base o circuito ilustrado na Fig.\ref{fig:circuit-biasTee-H}.

```{=latex}
\begin{figure}[h]
  \centering
  \begin{circuitikz}[american]
	  \draw (1, -1) coordinate(point1) to[R, l=$R_s$, *-] ++(0, -2) to[vsource, l=$V_s$] ++(0, -1.5) to[short] ++(3, 0) coordinate(point2) node[ground]{} ;
	  \draw (point1) to[C, l=C, a=$X_C$, i^>=$I_s$] ++(3, 0) coordinate(point3) to[L, l=L, a=$X_L$, i>^=$I_{dc}$] (point2) ;
	  \draw (point3) to[short, -*] ++(2, 0) to[R, l=$R_L$, i>^=$I_{L2}$] ++(0, -3.5) to[short] (point2) ;
  
    % Add the marker for V_{L2}
    \node at (point1) [above] {$V_{i2}$};
    \node at ($(point3) + (2, 0)$) [above] {$V_{o2}$};
  \end{circuitikz}
  \caption{Função de transferência do circuito com \textit{bias-Tee}}
  \label{fig:circuit-biasTee-H}
\end{figure}
```

Dessa forma, a função de transferência do circuito é dada por

$$
  H(j\omega) = \frac{V_{o2}}{V_{i2}}=\frac{X_LR_L}{X_LX_C+R_LX_C+X_LR_L}
$$

em que, aqui, $X_L=j\omega L$ e $X_C=(j\omega C)^{-1}$. Assim, a tensão na carga pode ser calculada como

$$
  V_{o2}=H(j\omega)V_{i2}
$$

E a potência dissipada pela carga pode ser calculada por

$$
  P_{L2}=\frac{V_{o2}^2}{2R_L}
$$

Semelhantemente, pode-se calcular a potência dissipada na carga sem o *bias-tee*

$$
  P_{L1}=\frac{V_{o1}^2}{2R_L}
$$

Visualizando o circuito apresentado na Fig.\ref{fig:circuit-no-biasTee-transfer} chega-se à conclusão de que $V_{i1}=V_{o1}$.

```{=latex}
\begin{figure}[h]
  \centering
  \begin{circuitikz}[american]
	  \draw (0.5, -1.5) coordinate(point1) to[vsource, l=$V_s$] ++(0, -2) to[short] ++(4.5, 0) coordinate(point2) ;
	  \draw (point1) to[R, l=$R_s$] ++(0, 2) to[short, *-*] ++(4.5, 0) to[R, l=$R_L$, i>^=$I_{L1}$, *-] (point2) ;

    % Add the marker for V_{L1}
    \node at (5, 0.5) [above right] [above] {$V_{o1}$};
    \node at ($(point1) + (0, 2)$) [above] {$V_{i1}$};
  \end{circuitikz}
  \caption{Circuito sem \textit{bias-Tee}}
  \label{fig:circuit-no-biasTee-transfer}
\end{figure}
```

Dessa forma, a equação torna-se

$$
  P_{L1}=\frac{V_{i1}^2}{2R_L}
$$

Portanto, o *insertion loss*, IL, do circuito é dado por

$$
\begin{split}
  \text{IL}&=\frac{P_{L1}}{P_{L2}}\implies\\
  &=\frac{V_{i1}^2}{V_{i2}^2H(j\omega)^2}
\end{split}
$$

Pela [Eq. @eq-voltage-before] tem-se a tensão antes do acoplamento do DUT. A tensão de entrada após o acoplamento do DUT é dada por

$$
  \begin{split}
    I_s&=I_{dc}+I_{L2}\implies\\
    \frac{V_s+V_{i2}}{R_s}&=V_o\left(\frac{1}{R_L}+\frac{1}{X_L}\right)\implies\\
    V_s-V_{i2}&=R_sV_{i2}H(j\omega)\left(\frac{1}{R_L}+\frac{1}{X_L}\right)
  \end{split}
$$

Assim, obtém-se

$$
  V_{i2}=\frac{R_LX_LV_s}{X_LR_sH(j\omega)+R_LR_sH(j\omega)+R_LX_L}
$$

Para facilitar o processo, calcula-se a raiz quadrada do *insertion loss*, ou seja

$$
  \begin{split}
    \sqrt{\text{IL}}&=\frac{V_sR_L}{(R_s+R_L)}\frac{X_LR_sH(j\omega)+R_LR_sH(j\omega)+R_LX_L}{R_LX_LV_sH(j\omega)}\implies\\
    &=\frac{1}{(R_s+R_L)}\frac{X_LR_sH(j\omega)+R_LR_sH(j\omega)+R_LX_L}{X_LH(j\omega)}\implies\\
    &=\frac{1}{(R_s+R_L)}\left(R_s+\frac{R_LR_s}{X_L}+\frac{R_L}{H(j\omega)}\right)
  \end{split}
$$

Substituindo a equação obtida para a função de transferência, $H(j\omega)$,

$$
  \begin{split}
    \sqrt{\text{IL}}&=\frac{1}{(R_s+R_L)}\left(R_s+\frac{R_LR_s}{X_L}+\frac{R_L}{H(j\omega)}\right)\implies\\
    &=\frac{1}{(R_s+R_L)}\left(R_s+\frac{R_LR_s}{X_L}+R_L\frac{X_LX_C+R_LX_C+X_LR_L}{X_LR_L}\right)\implies\\
    &=\frac{1}{(R_s+R_L)}\left(R_s+\frac{R_LR_s}{X_L}+\frac{X_LX_C+R_LX_C+X_LR_L}{X_L}\right)\implies\\
    &=\frac{1}{(R_s+R_L)}\left(\frac{R_sX_L+R_LR_s+X_LX_C+R_LX_C+X_LR_L}{X_L}\right)\implies\\
    &=\frac{R_sX_L+R_LR_s+X_LX_C+R_LX_C+X_LR_L}{X_LR_s+X_LR_L}
  \end{split}
$$

Se for feito $X_L=jX_L^{'}$ e $X_C=-jX_C^{'}$, essa equação resulta em

$$
  \begin{split}
    \sqrt{\text{IL}}&=\frac{R_sX_L^{'}-R_LX_C^{'}+X_L^{'}R_L-j(R_LR_s+X_L^{'}X_C^{'})}{X_L^{'}R_s+X_L^{'}R_L}
  \end{split}
$$ {#eq-insertion-loss-sqrt}





