---
title: Componentes Passivos em RF 
subtitle: Laboratório 07
author:
  - name: Bruno Alexandre Fraga
    email: bruno.fraga@posgrad.ufsc.br
    affiliations: 
        - id: some-tech
          name: Universidade Federal de Santa Catarina
          department: Departamento de Engenharia Elétrica e Eletrônica
          address: R. Delfino Conti
          city: Florianópolis
          state: Santa Catarina
          postal-code: 88040-370
abstract: |
  Este trabalho tem por objetivo consolidar a técnica de projeto de redes de casamento de impedância, em especial a técnica pela rede L. Para isso, é proposto realizar o casamento de impedância da saída de um amplificador para uma carga de 50 $\Omega$ de modo que a eficiência da potência dissipada na carga seja de 80%. Após algumas análises o projeto foi concluído com sucesso e realizada uma simulação Monte Carlo com 100 iterações para verificar a robustez do projeto por técnicas estatísticas. Os resultados obtidos foram brevemente discutidos.
keywords: 
  - Robustez
  - Adaptação de impedância
  - Análise estatística
date: last-modified
bibliography: bibliography.bib
format:
  elsevier-pdf:
    include-in-header:
      - text: |
          \usepackage{steinmetz}
          \usepackage[a4paper, margin=1in]{geometry}
          \usepackage{graphicx} % Required for inserting images
          \usepackage{circuitikz}
          \usepackage{amsmath}
          \usepackage{amssymb}
          \usepackage{amsthm}
          \usepackage{tikz}
          \usetikzlibrary{shapes,arrows}
          \usetikzlibrary{shapes,arrows,positioning,calc}

          \newcommand{\parallelsum}{\mathbin{\!/\mkern-5mu/\!}}
    keep-tex: true
    journal:
      name: RF Circuits
      formatting: preprint
      # model: 3p # Don't set a model with preprint
      cite-style: number
---

# Revisão




## Operação do BJT

A corrente de base $I_B$ de um transistor bipolar de junção (BJT) é dada por

$$
I_B = \frac{I_C}{\beta}
$$

onde $I_C$ é a corrente de coletor, $\beta$ é o ganho de corrente de base (ou fator de amplificação de corrente).

Para um BJT operando na região ativa, a corrente de coletor $I_C$ por ser obtida por

$$
I_C = I_se^{V_{BE}/V_T}
$$

onde $I_s$ é a corrente de saturação reversa, $V_T$ é a tensão térmica ($V_T = \frac{kT}{q}$, aproximadamente 26 mV a 300 K) e $V_{BE}$ é a tensão entre base e emissor.

Assim, a corrente de base $I_B$ também pode ser escrita como @sedra2014microelectronic

$$
I_B = \frac{I_s}{\beta}e^{V_{BE}/V_T}
$$

## Feedback degenerativo de emissor

O diagrama geral de um amplificador de transcondutância com *feedback* é apresentado na Fig.\ref{fig:feedback-amp}.

```{=latex}
\begin{figure}[!htb]
\centering
\begin{tikzpicture}

% Sum shape
\node[draw,
    circle,
    minimum size=0.6cm,
] (sum) at (0,0){};

\draw (sum.north east) -- (sum.south west)
    (sum.north west) -- (sum.south east);

\node[left=-1pt] at (sum.center){\tiny $+$};
\node[below] at (sum.center){\tiny $-$};

% Amplifier as a triangle rotated 90 degrees clockwise
\node[draw,
    isosceles triangle,
    isosceles triangle apex angle=60,
    minimum height=1.2cm,
    minimum width=1.6cm,
    shape border rotate=0,
    right=1cm of sum
] (amplifier) {$A$};

% Feedback network
\node [draw,
    minimum width=2cm, 
    minimum height=1.2cm, 
    below = 1cm of amplifier
]  (feedback) {$\zeta$};

% Arrows with text label
\draw[-stealth] (sum.east) -- (amplifier.west)
    node[midway,above]{$v_e$};

\draw[-stealth] (amplifier.east) -- ++ (1.25,0) 
    node[midway](output){}node[midway,above]{$i_o$};

\draw[-stealth] (output.center) |- (feedback.east);

\draw[-stealth] (feedback.west) -| (sum.south) 
    node[near end,left]{$v_f$};

% Input arrow for v_in (reversed direction)
\draw[stealth-] (sum.west) -- ++(-1,0) 
    node[midway,above]{$v_i$};

\end{tikzpicture}
\caption{Diagrama de bloco de um amplificador de transcondutância com feedback} 
\label{fig:feedback-amp}
\end{figure}
```
Quando um BJT possui um resistor de emissor $R_E$, a presença deste resistor introduz um feedback negativo que estabiliza o ponto de operação do transistor, reduzindo a sensibilidade do circuito às variações de $\beta$ (ganho de corrente de base) e outros motivos. Um amplificador com transistor BJT e um resistor $R_E$ de *feedback* pode ser visualizado na Fig.\ref{fig:original-circuit-v2}.

Analisando o diagrama, verifica-se que o ganho de malha aberta, $A$, do amplificador é dado por $g_m$, a condutância de transferência do transistor e o atenuador de *feedback*, $\zeta$, é o resistor de emissor, $R_E$.

```{=latex}
\begin{figure}[h]
  \centering

  \begin{circuitikz}
    \draw (0.98, 0) node[npn](nmos1){};
    \draw (nmos1.C) to[short, i_<=$I_C$] ++(0, 1) node[vcc]{} ;
    \draw (nmos1.E) to[R, l=$R_E$, i>^=$I_E$] (1, -3) node[ground]{} ;
    \draw (nmos1.B) to[short, i_<=$I_B$, -*] (-1, 0) ;
  \end{circuitikz}

  \caption{Circuito original}
  \label{fig:original-circuit-v2}
\end{figure}
```

A equação da corrente de saída, com base na Fig.\ref{fig:feedback-amp} é dada por

$$
  \begin{split}
    v_f&=i_o\zeta\implies\\
    v_e&=v_i-i_o\zeta\implies\\
    i_o&=A\left(v_i-i_o\zeta\right)\implies\\
    i_o&=Av_i-Ai_o\zeta\implies\\
    Av_i&=i_o\left(1+A\zeta\right)\implies\\
    \frac{v_i}{i_o}&=\frac{\left(1+A\zeta\right)}{A}\implies\\
    \frac{i_o}{v_i}&=\frac{A}{\left(1+A\zeta\right)}
  \end{split}
$$























Quando a corrente de coletor $I_C$ aumenta, a corrente de emissor $I_E$ também aumenta, pois $I_E\propto I_C$. Com o aumento de $I_E$, a queda de tensão sobre $R_E$, dada por $V_{RE} = I_ER_E$ também aumenta. Um aumento de $V_{RE}$ implica em um aumento de $V_E$ e, consequentemente, gera uma redução de $V_{BE}$, já que $V_{BE} = V_B - V_E$, gerando, assim, uma redução em $I_C$, compensando o aumento inicial de $I_C$.

Essa compensação reduz a sensibilidade da corrente de coletor $I_C$ a possíveis flutuações em $\beta$ ou de temperatura. Assim, o circuito se estabiliza em um ponto de operação mais estável, independentemente de variações nas características do BJT.

Com o resistor de emissor, a corrente de base $I_B$, corrente de coletor $I_C$, e a tensão base-emissor $V_{BE}$ têm uma relação que leva em conta a queda de tensão em $R_E$.

Para o circuito polarizado com $R_E$, a corrente de emissor $I_E$ é dada por

$$
I_E = \frac{V_E}{R_E} = \frac{V_B - V_{BE}}{R_E}
$$

Como a corrente de emissor $I_E\approx I_C$, pode-se aproximar a corrente de coletor $I_C$ como

$$
I_C \approx \frac{V_B - V_{BE}}{R_E}
$$

Essa expressão mostra que a corrente de coletor depende diretamente da tensão na base $V_B$ e é influenciada pelo valor do resistor de emissor $R_E$ @sedra2014microelectronic.





















## Série de Taylor

Para apresentar as demonstrações do fenômeno de intermodulação, antes é necessário abordar a expansão de Taylor, uma ferramenta matemática usada para aproximar funções em torno de um ponto específico $x = a$. A ideia é escrever a função como uma soma infinita de termos, onde cada termo envolve uma derivada da função no ponto de expansão. Quando a série é truncada nos primeiros termos, obtém-se uma aproximação polinomial da função original.

Para uma função $f(x)$, a expansão de Taylor em torno de um ponto $x = a$ é dada por

$$
f^{'}(x)=f(a) + f'(a)(x - a) + \frac{f''(a)}{2!}(x - a)^2 + \frac{f'''(a)}{3!}(x - a)^3 + \dots
$$ {#eq-taylor-series}

Cada termo da expansão representa uma correção que considera a variação da função em torno do ponto de operação $a$ @guidozzi2018cursoVol1.

## Produtos de intermodulação

No caso do transistor com feedback de emissor, a deia é expandir a função da corrente $I_C$ em torno de uma tensão de entrada (na base) $V_{i0}$. Então, aplica-se a expansão de Taylor para a função $I_C = f(V_i)$ em torno de $V_i = V_{i0}$. Para isso, substitui-se, $f(V_i) = I_C$, $a = V_{i0}$, e $\Delta V_i = \left(V_i - V_{i0}\right)$. Assim, a série de Taylor até a terceira ordem fica

$$
I_C^{'}=I_C(V_{i0}) + \left(V_i - V_{i0}\right)\frac{dI_C}{dV_i}\left(V_{i0}\right)  + \frac{\left(V_i - V_{i0}\right)^2}{2} \frac{d^2 I_C}{dV_i^2}\left(V_{i0}\right)  + \frac{\left(V_i - V_{i0}\right)^3}{6} \frac{d^3 I_C}{dV_i^3}\left(V_{i0}\right)+\dots
$$ {#eq-taylor-series-intermodulation}

onde $\frac{d^nI_C}{dV_i^n}\left(V_{i0}\right)$ é a derivada de orden $n$ da função $I_C$ em relação a $V_i$ avaliadas no ponto $V_{i0}$.

A fim de possibilitar os cálculos, são tomados somente os 3 primeiros termos da [Eq. @eq-taylor-series-intermodulation], levando a @razavi2011rf

$$
I_C\approx I_C(V_{i0}) + \left(V_i - V_{i0}\right)\frac{dI_C}{dV_i}\left(V_{i0}\right)  + \frac{\left(V_i - V_{i0}\right)^2}{2} \frac{d^2 I_C}{dV_i^2}\left(V_{i0}\right)  + \frac{\left(V_i - V_{i0}\right)^3}{6} \frac{d^3 I_C}{dV_i^3}\left(V_{i0}\right)
$$

Simplificando $V_{i0}=0$ e consequentemente $I_C(V_{i0})=0$

$$
I_C\approx V_i\frac{dI_C}{dV_i}(0) + \frac{V_i^2}{2} \frac{d^2 I_C}{dV_i^2}(0)  + \frac{V_i^3}{6} \frac{d^3 I_C}{dV_i^3}(0)
$$

Escrevendo de uma forma mais sucinta, obtém-se

$$
I_C\approx V_i\alpha_1+V_i^2\alpha_2+V_i^3\alpha_3
$$

em que $\alpha_1=\frac{dI_C}{dV_i}(0)$, $2\alpha_2=\frac{d^2 I_C}{dV_i^2}(0)$ e $6\alpha_3=\frac{d^3 I_C}{dV_i^3}(0)$. 
















































# References {-}
